### PR TITLE
Add video to python example

### PR DESCRIPTION
**Pull request by victorwuky**

### CODE REVIEW

**Comment by victorwuky** [comment]
@ellenkorbes : I think we should add your video to the doc, especially if it's a great companion video, which it is! (Don't know where it should belong though. Feel free to move around if you agree we should add it.)

**Comment by ellenkorbes** [comment]
Wait, why did you close the PR before merging?

**Comment by victorwuky** [comment]
@ellenkorbes: I didn’t hear from you so I figured this wasn’t important to add should we add this?

**Comment by ellenkorbes** [comment]
Yes. Probably here? https://docs.tilt.dev/example_python.html

**Comment by ellenkorbes** [comment]
Yes! I'll review this tomorrow.

**Pull request merged**
