### PR TITLE
Blog post: Private team snapshots

### PR DESCRIPTION
**Pull request by victorwuky**
screencapture-localhost-4002-2020-07-31-private-team-snapshots-html-2020-07-14-13_40_49

### CODE REVIEW

**Comment by victorwuky** [comment]
@hyu : I'm done the initial draft here. Just pending screenshots/gifs of some of the improvements in https://app.clubhouse.io/windmill/epic/7991/snapshots-ux-improvements

**Comment by maiamcc** [comment]
General comment: I'm not sure that this blog post will resonate with someone who's not already sold on snapshots. A more persuasive format might be:
1. brief recap of what snapshots are/why they're great
2. ...and we've added this functionality that unlocks this feature for a whole new swath of users
3. why [private] snapshots are especially awesome when used on your team
4. toward our Tilt Cloud vision.

**Comment by hyu** [comment]
I cosign @maiamcc's feedback. Some additional points:

1. Did you see Dan Miller's earlier blog post, [Solving the Laggy Human Shell](https://blog.tilt.dev/2019/10/01/solving-the-laggy-human-shell-problem.html)? He writes:

~~~
Introducing Tilt Snapshots

A snapshot is a link that you can send to someone that will allow them to interactively explore your current Tilt state. This is useful for async debugging and adding context to bug reports. They look like pretty much just like Tilt, but frozen in time. Here’s an example:
~~~

Now, I'm not going to claim that people are such close followers of the Tilt blog that they would be like, "Hey, didn't you already launch this feature?!" But, _I_ know the context and feel mild embarassment that we might come off like we have goldfish memory!

This is another reason that I really like Maia's framing of "...and we've added this functionality that unlocks this feature for a whole new swath of users" There's also compelling story we can tell here about our product development process, where we listen to customers and incorporate their feedback. (AND one more power move would be to address this challenge, "Wait, isn't 'private' snapshots an obvious feature?" — Aka, we could speak to the fact that we've spent the intervening time since Dan Miller's post in October really building out our team platform. So Private Team Snapshots is the culmination of a lot of cool features coming together.)

&nbsp; 
2. We should be careful with using the term "DevEx"...that is a useful internal shorthand for the customer we want to target.  But not everyone self-identifies as “DevEx”. That term might even be a turn off, like “Huh? I’m a tech lead / engineer / devops, not ‘DevEx’…this must not be for me.”

**Comment by victorwuky** [comment]
@hyu @maiamcc : Thanks for the feedback. I'm going to get Dan B to review https://github.com/tilt-dev/tilt.build/pull/673 within the next week or so, and then this one afterward. So we can be aligned on the messaging in both places. Hopefully that should dovetail nicely with work wrapping up by Han? (For https://app.clubhouse.io/windmill/epic/7991/snapshots-ux-improvements.)

**Comment by victorwuky** [comment]
@maiamcc : I chatted briefly with Dan about this. (And also https://github.com/tilt-dev/tilt.build/pull/673/.) At least this week, Dan is focused on other priorities. 

@hyu is focused on carving out next steps for snapshots and I will be supporting them. See https://app.clubhouse.io/windmill/story/8486. So I think we don't have to publish this blog post anytime soon, and we can roll this blog post into that process. I'll comment further on https://github.com/tilt-dev/tilt.build/pull/673 though, as I don't want that one to get stale.

**Pull request closed without merging**
